---
name: Feature request
description: Suggest an idea for this project
labels: ["is: feature-request"]

body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for proposing a new feature request!

        Please make sure of the following:
        - You agree to follow [this project's Code of Conduct](https://github.com/libretime/organization/blob/main/CODE_OF_CONDUCT.md)
        - You have verified that your issue [hasn't already been created](https://github.com/libretime/libretime/issues?q=is%3Aopen+is%3Aissue+label%3A%22is%3A+feature-request%22).
        - You will gather and properly fill all the requested information.

  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request.
