style: github
template: CHANGELOG.md.tpl
info:
  title: CHANGELOG
  repository_url: https://github.com/libretime/libretime
options:
  commits:
    filters:
      Type: [feat, fix, docs, test, ci]
    sort_by: Date
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      docs: Documentation
      test: Tests
      ci: CI
    sort_by: Custom
    title_order: [feat, fix, docs, test, ci]
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
