name: API Client

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/api-client.yml
      - api-client/**
      - shared/**

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/api-client.yml
      - api-client/**
      - shared/**

  schedule:
    - cron: 0 1 * * 1

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: api-client
