name: Shared

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/shared.yml
      - shared/**

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/shared.yml
      - shared/**

  schedule:
    - cron: 0 1 * * 1

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: shared
